### ISSUE TITLE
вопрос по подключению

### ISSUE THREAD

**Issue by pashos** [SoftFx/TTWebSockets-Examples#1]
Пытаемся подключится по Websocket:
1. Подключились успешно
2. Отправили корректное сообщение Login (с правильной сигнатурой, и т.д.)
3. В ответ получили сообщение об успешном логине ( Response: 'Login', Result: 'ok’)
4. После этого ожидается что прийдут нотифиекйшны ‘TradeSessionInfo' и ‘Account', что, как я понял, должно указывать на то, что началась торговая сессия. Но эти сообщения не приходят, и после логина ничего вобще больше не приходит от сервера.
5. После этого при попытке отправить какой-либо запрос (например Trades) от сервера приходит ответ, что такой запрос не поддерживается (к примеру 'Unsupported request - Trades', 'Unsupported request - Assets’, 'Unsupported request - Account’, 'Unsupported request - TradeSessionInfo’, 'Unsupported request - TradeCreate’, и т.д.)
6. Единственный запрос на который можно получить хоть какой-то ответ, это запрос ‘SessionInfo'. Но в ответе на этот запрос почему-то сказано 'TradeAllowed: false’, хотя должно быть 'true'. В настройках для этого WebApiId полe Rights установлено в значение ‘Full’, поэтому ожидается что значение поля ‘TradeAllowed’ должно быть ‘true'.
В результате, залогинится через WebsocketAPI получилось, но больше никаких действий сделать не удается.
Вроде бы, все сделали согласно документации. Подскажите что надо сделать чтобы сервер принимал запросы и чтобы можно было торговать через WS API?

**Comment by chronoxor** [comment]
1. Чтобы получать нотификации по изменениям котировок нужно подписаться на котировки по одному или нескольким символам (FeedSubscribe request). Полсе упешной подписки нотификации с котировками будут приходит в FeedTick notification.
2. Запросы по торговле нужно отправлять по другому WebSocket соединению:

WebSocket Feed порт 2083 - https://cryptottdemowebapi.xbtce.net:8443/api/doc/WebSockets-Feed

WebSocket Trade порт 2087 - https://cryptottdemowebapi.xbtce.net:8443/api/doc/WebSockets-Trade
